AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  Exclude:
    - 'Rakefile'
    - 'config/**/*'
    - 'Gemfile'
    - 'Guardfile'
    - 'db/**/*'
    - 'bin/**/*'
    - 'tmp/**/*'
    - 'spec/spec_helper.rb'

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/MethodLength:
  Max: 10

Style/FrozenStringLiteralComment:
  Enabled: true

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*.rb'

Lint/UselessAssignment:
  Enabled: true

Metrics/AbcSize:
  Max: 15

Metrics/ClassLength:
  Max: 100

Metrics/ModuleLength:
  Max: 100

Metrics/ParameterLists:
  Max: 5

Metrics/PerceivedComplexity:
  Max: 7

Style/Documentation:
  Enabled: false