:concurrency: 3
:timeout: 60
:verbose: true
:queues:
  - critical
  - default
  - mailers
  - active_storage_analysis
  - active_storage_purge
:schedule:
  manage_abandoned_carts:
    cron: "0 * * * *" # Every hour
    class: "ManageAbandonedCartsJob"